OnlineShoppingStore.WebUI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.Domain.Entities;
using OnlineShoppingStore.WebUI.Models;

namespace OnlineShoppingStore.WebUI.Controllers
{
#pragma warning disable CS0246 // The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
    public class CartController : Controller
#pragma warning restore CS0246 // The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
    {
        private IProductRepository repository;
        private IOrderProcessor orderProcessor;
        public CartController(IProductRepository repo, IOrderProcessor proc)
        {
            repository = repo;
            orderProcessor = proc;
        }

#pragma warning disable CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        public ViewResult Index(Cart cart, string returnUrl)
#pragma warning restore CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            return View(
                new CartIndexViewModel { Cart = cart, ReturnUrl = returnUrl});
        }
        
#pragma warning disable CS0246 // The type or namespace name 'PartialViewResult' could not be found (are you missing a using directive or an assembly reference?)
        public PartialViewResult Summary(Cart cart)
#pragma warning restore CS0246 // The type or namespace name 'PartialViewResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            return PartialView(cart);
        }
        //this HttpGet - if not mention attribute, it will be HttpGet
#pragma warning disable CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        public ViewResult Checkout()
#pragma warning restore CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            return View(new ShippingDetails());
        }
#pragma warning disable CS0246 // The type or namespace name 'HttpPostAttribute' could not be found (are you missing a using directive or an assembly reference?)
#pragma warning disable CS0246 // The type or namespace name 'HttpPost' could not be found (are you missing a using directive or an assembly reference?)
        [HttpPost]
#pragma warning restore CS0246 // The type or namespace name 'HttpPost' could not be found (are you missing a using directive or an assembly reference?)
#pragma warning restore CS0246 // The type or namespace name 'HttpPostAttribute' could not be found (are you missing a using directive or an assembly reference?)
#pragma warning disable CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        public ViewResult Checkout(Cart cart, ShippingDetails shippingDetails)
#pragma warning restore CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            if (cart.Lines.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your cart is empty!");
            }

            if (ModelState.IsValid)
            {
                orderProcessor.ProcessOrder(cart, shippingDetails);
                cart.Clear();
                return View("Completed");
            }
            else
            {
                return View(new ShippingDetails());
            }

            
        }

#pragma warning disable CS0246 // The type or namespace name 'RedirectToRouteResult' could not be found (are you missing a using directive or an assembly reference?)
        public RedirectToRouteResult AddToCart(Cart cart, int productId, string returnUrl)
#pragma warning restore CS0246 // The type or namespace name 'RedirectToRouteResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                //add product to cart - will need to create helper method
                cart.AddItem(product, 1);
            }

            return RedirectToAction("Index", new {returnUrl});
        }

#pragma warning disable CS0246 // The type or namespace name 'RedirectToRouteResult' could not be found (are you missing a using directive or an assembly reference?)
        public RedirectToRouteResult RemoveFromCart(Cart cart, int productId, string returnUrl)
#pragma warning restore CS0246 // The type or namespace name 'RedirectToRouteResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            Product product = repository.Products.FirstOrDefault(p => p.ProductId == productId);
            if (product != null)
            {
                cart.RemoveLine(product);
            }

            return RedirectToAction("Index", new {returnUrl});
        }
    }
}

OnlineShoppingStore.WebUI/Controllers/NavController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Abstract;

namespace OnlineShoppingStore.WebUI.Controllers
{
#pragma warning disable CS0246 // The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
    public class NavController : Controller
#pragma warning restore CS0246 // The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
    {
        private IProductRepository repository;

        public NavController(IProductRepository repo)
        {
            repository = repo;
        }
        //the manu will return partial result
#pragma warning disable CS0246 // The type or namespace name 'PartialViewResult' could not be found (are you missing a using directive or an assembly reference?)
        public PartialViewResult Menu(string category = null)
#pragma warning restore CS0246 // The type or namespace name 'PartialViewResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            //pass this cagetory to the view
            ViewBag.SelectedCategory = category;
            //select from the database ienumerable 
            IEnumerable<string> categories = repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);
            return PartialView(categories);
        }
    }
}

OnlineShoppingStore.WebUI/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OnlineShoppingStore.Domain.Abstract;
using OnlineShoppingStore.WebUI.Models;

namespace OnlineShoppingStore.WebUI.Controllers
{
#pragma warning disable CS0246 // The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
    public class ProductController : Controller
#pragma warning restore CS0246 // The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)
    {
        //Use contractor injection
        private readonly IProductRepository repository;
        public int PageSize = 4;
        public ProductController(IProductRepository repo)
        {
            repository = repo;
        }
#pragma warning disable CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        public ViewResult List(string category, int page = 1)
#pragma warning restore CS0246 // The type or namespace name 'ViewResult' could not be found (are you missing a using directive or an assembly reference?)
        {
            ProductsListViewModel model = new ProductsListViewModel
            {
                Products = repository.Products
                    .Where(p => category == null || p.Category == category)
                    .OrderBy(p => p.ProductId)
                    .Skip((page -1) * PageSize)
                    .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = page,
                    ItemsPerPage = PageSize,
                        // if the first condition is true, execute the first repository.prodcuts.count()
                    TotalItems = category == null? 
                                 repository.Products.Count() : 
                        // if the condition is fall then execute the bellow 
                        repository.Products.Where(p => p.Category == category).Count()
                },
                CurrentCategory = category
            };
            return View(model);
     
        }
    }
}

OnlineShoppingStore.WebUI/Views/Shared/ProductSummary.cshtml
@model OnlineShoppingStore.Domain.Entities.Product
<div class="well">
    <h3>
        <strong>@Model.Name</strong>
        <span class="pull-right label label-primary">@Model.Price.ToString("c")</span>
    </h3>
    @using (Html.BeginForm("AddToCart", "Cart"))
    {
        <div class="pull-right">
            @Html.HiddenFor(x => x.ProductId)
            @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
            <input type="submit" class="btn btn-success" value="Add to cart"/>
        </div>
    }

    <span class="lead">@Model.Description</span>
</div>

OnlineShoppingStore.WebUI/Views/Shared/_AdminLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>
<body>
<div>
    <div>
        @if (TempData["message"] != null)
        {
            <div class="alert alert-success">@TempData["message"]</div>
        }
        @{
            var userName = HttpContext.Current.User.Identity.Name;
            if (userName != "")
            {
                <h3>
                    @Html.ActionLink("Online Shopping Store", "List", "Product")
                    <span class="btn-info btn pull-right">
                        @*@Html.ActionLink(HttpContext.Current.User.Identity.Name, "Logout", "Account")*@
                        @Html.ActionLink(userName + " - Logout", "Logout", "Account")
                    </span>   
                </h3>
        }
        }
        @RenderBody()
    </div>
</div>
</body>
</html>

OnlineShoppingStore.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Online Shoping Store</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse" role="navigation">
        <a class="navbar-band" href="#">
            <span class="hidden-xs">Online Shopping Store</span>
            <div class="visible-xs">Online</div>
            <div class="visible-xs">Shopping</div>
            <div class="visible-xs">Store</div>
        </a>
        @Html.Action("Summary", "Cart")
    </div>
    <div class="row panel">
        <div id="categoris" class="col-lg-3">
            @Html.Action("Menu", "Nav") @*//action,controller*@
        </div>
        <div class="col-lg-7">
            @RenderBody()
        </div>
    </div>
</body>
</html>